### ISSUE TITLE
Úkol č. 1

### ISSUE THREAD

**Issue by AnetaCapova** [AnetaCapova/Ukoly_AC#2]
https://github.com/AnetaCapova/Ukoly_AC/blob/main/ukol_1.py 

Odevzdávám úkol č. 1, ale je to špatně, prosím o pošťouchnutí, ještě nad tím budu přemýšlet, ale nějak jsem se zasekla u toho, jak zadat, když hodnota je True, tak napiš: "Balík byl předán kurýrovi". Předem moc děkuji za pomoc.

**Comment by AnetaPopelova** [comment]
Prijde mi, ze se snazis vyresit dve veci naraz.

Zkontrolovat jestli je kod baliku ve slovniku (to jde treba takhle `if kod_baliku in baliky:`) a zaroven koukat, jestli predani je true/false (`if baliky[kod_baliku] == True:`).

Zeptala bych se nejprve, jestli balik existuje a pak vlozila druhou podminku vyhodnocujici predani. 

Ty jsi pouzila metodu `values`, ktera vraci VSECHNY hodnoty ze slovniku. Kdybys ji nekdy potrebovala pouzit, nezapominej na zavorku `slovnik.values()`.

**Comment by AnetaCapova** [comment]
https://github.com/AnetaCapova/Ukoly_AC/blob/main/ukol_1.py

Tak si myslím, že hotovo, moc děkuju za pomoc!

**Comment by AnetaPopelova** [comment]
💯
